FROM node:18-alpine AS build
WORKDIR /app
COPY . .

# Nuevas variables de entorno
ARG PUBLIC_URL
ARG REACT_APP_BASE_URL
ARG REACT_APP_SOCKET_TRACKER
ARG REACT_APP_SOCKET_BACK
ARG REACT_APP_DEFAULTAUTH
ARG REACT_APP_APIKEY
ARG REACT_APP_AUTHDOMAIN
ARG REACT_APP_DATABASEURL
ARG REACT_APP_PROJECTID
ARG REACT_APP_STORAGEBUCKET
ARG REACT_APP_MESSAGINGSENDERID
ARG REACT_APP_APPID
ARG REACT_APP_MEASUREMENTID



# Nuevas variables de entorno
ENV PUBLIC_URL=$PUBLIC_URL
ENV REACT_APP_BASE_URL=$REACT_APP_BASE_URL
ENV REACT_APP_SOCKET_TRACKER=$REACT_APP_SOCKET_TRACKER
ENV REACT_APP_SOCKET_BACK=$REACT_APP_SOCKET_BACK
ENV REACT_APP_DEFAULTAUTH=$REACT_APP_DEFAULTAUTH
ENV REACT_APP_APIKEY=$REACT_APP_APIKEY
ENV REACT_APP_AUTHDOMAIN=$REACT_APP_AUTHDOMAIN
ENV REACT_APP_DATABASEURL=$REACT_APP_DATABASEURL
ENV REACT_APP_PROJECTID=$REACT_APP_PROJECTID
ENV REACT_APP_STORAGEBUCKET=$REACT_APP_STORAGEBUCKET
ENV REACT_APP_MESSAGINGSENDERID=$REACT_APP_MESSAGINGSENDERID
ENV REACT_APP_APPID=$REACT_APP_APPID
ENV REACT_APP_MEASUREMENTID=$REACT_APP_MEASUREMENTID

COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY . ./
RUN npm run build

FROM nginx:1.19-alpine
COPY --from=build /app/dist /usr/share/nginx/html
